- name: printing with prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name -
  - name: DURATION
    prompt: Please enter the duration of course -
  - name: TRAINER
    prompt: Please enter the Triner Name -
    
  tasks:
  - name: prompt printing
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }} with the duration of {{ DURATION }} and the tariner is {{ TRAINER }}" 