- name: printing with prompt
  hosts: local
  connection: local
  tasks:
  - name: prompt printing
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }} with the duration of {{ DURATION }} and the tariner is {{ TRAINER }}" 