# - name: printing with args
#   hosts: local
#   connections: local
#   tasks:
#   - name: args printing
#     ansible.builtin.debug:
#       msg: "The course is {{ COURSE }} with the duration of {{ DURATION }} and the tariner is {{ TRAINER }}"
- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"