- name: Nginx Installing with condition
  hosts: web
  become: yes
  tasks:
  - name: if os is RHEL-install  nginx
    ansible.builtin.dnf:
    - name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: if os is Debian-install  nginx
    ansible.builtin.apt:
    - name: nginx
      state: installed
    when: ansible_os_family == "Debian"
  