- name: printing with filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "the name is {{ person | default('Ramesh') }}"
  
  - name: convert string to list 
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "the fruits are {{ fruits | split(',') }}"

  - name: convert map to list # map=dict ; list=item
    vars:
      course:
        name: ansible
        duration: 10hrs
        triner: SivaKumarReddy
    ansible.builtin.debug:
      msg: "the course is: {{ course | dict2items }}"

  - name: list to map # map=dict ; list=item
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'triner', 'value': 'SivaKumarReddy'}
    ansible.builtin.debug:
      msg: "the course is: {{ course | items2dict }}"

  - name: upper to lower
    tags:
    - uppertolower
    vars:
      name: "PARTHU REDDY"
    ansible.builtin.debug:
      msg: "hello this is: {{name}} upper-to-lower {{ name | lower }}"

  - name: lower to upper
    tags:
    - lowertoupper
    vars:
      name: "parthu reddy"
    ansible.builtin.debug:
      msg: "hello this is: {{name}} lower-to-upper {{ name | upper }}"

  - name: min and max
    tags:
    - minandmax
    vars:
      numbers: [1,2,3,4,4,5,6,7,8,23,44,566,5655]
    ansible.builtin.debug:
      msg: "min is {{ numbers|min }}, and max is {{numbers|max}} "