- name: printing with filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "the name is {{ person | default('Ramesh') }}"
  
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "the fruits are {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        triner: SivaKumarReddy
    ansible.builtin.debug:
      msg: "the course is: {{ course }}"