- name: printing with filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "the name is {{ person | default('Ramesh') }}"
  
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "the fruits are {{ fruits }}"