- name: shell vs Command
  hosts: local
  connection: local
  tasks:
  - name: shell and command
    ansible.builtin.command: ls -lt
    register: command_result

  - name: getting result
    ansible.builtin.debug:
      msg: "{{ command_result }}"