- name: creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-000fc1916202c5bb1
    sg_id: sg-0b030fd5e73eac564
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: parthudevops.space
    instances:
    - mysql
    - backend
    - frontend
  tasks:

  - name: installing required libs
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
    - boto3
    - botocore

  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: printing ec2 info
  #   ansible.builtin.debug:
  #     msg: "{{ec2_info}}"
  - name: print private IP addresses
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: creating private r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"

  - name: create public ip for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ec2_info.results}}"
    when: item.item == "frontend"